import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { GlobalStateProvider } from "@/components/GlobalContext";
import DictionaryMenu from "@/components/root/DictionaryMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Julevbágo - Samisk språkverktøy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col`}>
        <div className="h-screen relative flex flex-col">
          <GlobalStateProvider>
            <Navbar />
            <div className="mt-14">{children}</div>
            <DictionaryMenu />
          </GlobalStateProvider>
        </div>
      </body>
    </html>
  );
}
